CITIES = [
    "London",
    "Oxford",
    "Cambridge",
    "Bath",
    "Windsor",
    "Paris",
    "Versailles",
    "Giverny",
    "Reims",
    "Mont Saint-Michel",
    "Rome",
    "Florence",
    "Naples",
    "Pompeii",
    "Tivoli",
    "Tokyo",
    "Kyoto",
    "Osaka",
    "Nara",
    "Hakone",
    "New York City",
    "Brooklyn",
    "Boston",
    "Philadelphia",
    "Washington, D.C.",
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Al Ain",
    "Fujairah",
    "Singapore",
    "Sentosa",
    "Pulau Ubin",
    "Johor Bahru",
    "Batam",
    "Bangkok",
    "Ayutthaya",
    "Pattaya",
    "Chiang Mai",
    "Phuket",
    "Sydney",
    "Blue Mountains",
    "Canberra",
    "Hunter Valley",
    "Wollongong",
    "Barcelona",
    "Montserrat",
    "Girona",
    "Sitges",
    "Tarragona"
]